version: "3.7"

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ha-config:/config
      - localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PI_HOLE_PASSWORD}
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
      PGDATA: ${PGSQL_DATA}
    ports:
      - 5432:5432
    volumes:
      - pgdata:${PGSQL_DATA}
volumes: 
  etc-pihole:
  etc-dnsmasq.d:
  pgdata:
  ha-config:
  localtime:
