version: "3.7"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PI_HOLE_PASSWORD}
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes: 
  etc-pihole:
  etc-dnsmasq.d:
