version: "3.7"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PI_HOLE_PASSWORD}
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
    ports:
      - 5432:5432
volumes: 
  etc-pihole:
  etc-dnsmasq.d:
