www:
	container_name: www
	build: www
	ports:
		- 3000:3000
	volumes:
		- ./www:/www
    environment:
		MYSQL_HOST: ${MYSQL_HOST}
		MYSQL_USER: ${MYSQL_USER}
		MYSQL_PASSWORD: ${MYSQL_PASSWORD}
		MYSQL_DB: ${MYSQL_DB}
nginx:
	image: 'jc21/nginx-proxy-manager:latest'
	ports:
		- '8080:80'
		- '8081:81'
		- '4443:443'
	environment:
		DB_MYSQL_HOST: "mysql"
		DB_MYSQL_PORT: 3306
		DB_MYSQL_USER: "root"
		DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
		DB_MYSQL_NAME: ${MYSQL_DB}
	volumes:
		- nginx:/data
		- letsencrypt:/etc/letsencrypt
mysql:
	container_name: mysql
	build: mysql
	volumes: 
		- mysql:/var/lib/mysql
	environment: 
		MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
		MYSQL_DATABASE: ${MYSQL_DB}
